### ISSUE TITLE
Installation keeps failing on RPi B+ with Raspbian 

### ISSUE THREAD

**Issue by WouterDS** [zaphod1984/node-piglow#12]
pi@raspberrypi3 /var/www/dslr-control$ npm install piglow --save                                                                                                                 
	npm WARN package.json DSLRCamControl@1.0.0 No description
	npm WARN package.json DSLRCamControl@1.0.0 No repository field.
	npm WARN package.json DSLRCamControl@1.0.0 No README data
	/
	> i2c@0.1.8 install /var/www/dslr-control/node_modules/piglow/node_modules/i2c
	> node-gyp rebuild

	child_process: customFds option is deprecated, use stdio instead.
	make: Entering directory '/var/www/dslr-control/node_modules/piglow/node_modules/i2c/build'
	  CXX(target) Release/obj.target/i2c/src/i2c.o
	make: g++: Command not found
	i2c.target.mk:81: recipe for target 'Release/obj.target/i2c/src/i2c.o' failed
	make: *** [Release/obj.target/i2c/src/i2c.o] Error 127
	make: Leaving directory '/var/www/dslr-control/node_modules/piglow/node_modules/i2c/build'
	gyp ERR! build error 
	gyp ERR! stack Error: `make` failed with exit code: 2
	gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
	gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
	gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
	gyp ERR! System Linux 3.12-1-rpi
	gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
	gyp ERR! cwd /var/www/dslr-control/node_modules/piglow/node_modules/i2c
	gyp ERR! node -v v0.12.0
	gyp ERR! node-gyp -v v1.0.2
	gyp ERR! not ok 
	npm ERR! Linux 3.12-1-rpi
	npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "piglow" "--save"
	npm ERR! node v0.12.0
	npm ERR! npm  v2.5.1
	npm ERR! code ELIFECYCLE

	npm ERR! i2c@0.1.8 install: `node-gyp rebuild`
	npm ERR! Exit status 1
	npm ERR! 
	npm ERR! Failed at the i2c@0.1.8 install script 'node-gyp rebuild'.
	npm ERR! This is most likely a problem with the i2c package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     node-gyp rebuild
	npm ERR! You can get their info via:
	npm ERR!     npm owner ls i2c
	npm ERR! There is likely additional logging output above.

	npm ERR! Please include the following file with any support request:
	npm ERR!     /var/www/dslr-control/npm-debug.log

Full *npm-debug.log*: http://cl.ly/ZsSg/direct

**Comment by WouterDS** [comment]
Sorry nvm, I was missing g++.

**Comment by zaphod1984** [comment]
np, hope you like it!
